#ifndef COMMON_H
#define COMMON_H

#define RENDER_WIDTH 128
#define RENDER_HEIGHT 128
#define RENDER_SIZE RENDER_WIDTH *RENDER_HEIGHT
#define WINDOW_SCALE 8
#define WINDOW_HEIGHT RENDER_HEIGHT *WINDOW_SCALE
#define WINDOW_WIDTH RENDER_WIDTH *WINDOW_SCALE

typedef enum {
    STATUS_SUCCESS = 0,
    STATUS_ERROR = -1,
    STATUS_RENDER_ERROR = -2,
} status_code;

#endif
